batch_transform:
  target: degradation.batch_transform.RealESRGANBatchTransform
  params:
    out_size: 256 
    crop_type: center

    use_hflip: false
    use_rot: false

    blur_kernel_size: 21
    kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob: 0.1
    blur_sigma: [0.2, 3]
    betag_range: [0.5, 4]
    betap_range: [1, 2]

    blur_kernel_size2: 21
    kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
    kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
    sinc_prob2: 0.1
    blur_sigma2: [0.2, 1.5]
    betag_range2: [0.5, 4]
    betap_range2: [1, 2]

    final_sinc_prob: 1.0
    use_sharpener: false
    resize_hq: false
    # Queue size of training pool, this should be multiples of batch_size.
    queue_size: 256
    # the first degradation process
    resize_prob: [0.2, 0.7, 0.1] # up, down, keep
    resize_range: [0.5, 1.5]
    gaussian_noise_prob: 1.0
    noise_range: [5, 7]
    poisson_scale_range: [0.05, 3]
    gray_noise_prob: 0.5
    jpeg_range: [60, 90]

    # the second degradation process
    stage2_scale: 5 
    second_blur_prob: 1.0
    resize_prob2: [0.3, 0.4, 0.3] # up, down, keep
    resize_range2: [0.7, 1.2]
    gaussian_noise_prob2: 1.0
    noise_range2: [5, 7]
    poisson_scale_range2: [0.05, 2.5]
    gray_noise_prob2: 0.5
    jpeg_range2: [60, 90]
